services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./app:/pod/app
    restart: unless-stopped